//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Santander.SQL.EFServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountOperations
    {
        public int AccountOperationId { get; set; }
        public string Account { get; set; }
        public System.DateTime OperationDate { get; set; }
        public int OperationTypeId { get; set; }
        public string OperationStatus { get; set; }
    
        public virtual OperationTypes OperationTypes { get; set; }
    }
}
